In [ ]:

Algo

1. Initialize Population(group of chromosomes)

2. Selection of 2 Chromosomes(parents) based on FITNESS

3. Crossover (between selected parent chromosomes generate 2 childs)

4. Mutation (bit inversion)

5. Fitness calculation

6. Update Population

7. repeat from step 2 until we get desired fitness


In [1]:

import numpy as np


##1. Initial parent population intialization
pop=np.random.randint(0,2,(4,5))
print("Parent population",pop)


##
for lp in range(1,6):
    ##converting binary to decimal
    def bintodec(b):
        dec,p=0,0
        for i in range(len(b),0,-1): 
            dec+=b[i-1]*pow(2,p)
            p+=1
        return dec


    ##finding fitness(decimal,sum of whole population)
    def fitness(p):
        f=np.empty((len(p)), dtype='int')   
        for i in range(len(p)):
            f[i]=bintodec(p[i])
        return (f,sum(f))


    ##Finding parent population fitness
    f,fit=fitness(pop)
    #print("Parent population genetypes",pop)
    print("Parent population phonotypes",f)
    print("Parent population fitness",fit)


    ##Generating new 2childs from 2parents
    def crossover(p1,p2):
        d=np.random.randint(1,len(p1))
        print("parent ",p1,"parent ",p2,"divided at",d)
        c1=np.concatenate([p1[0:d],p2[d:]])
        c2=np.concatenate([p2[0:d],p1[d:]])
        return c1,c2


    ##child creation using crossover
    c=np.empty((pop.shape), dtype='int')
    for i in range(0,(len(pop)/2)*2,2):
        c[i],c[i+1]=crossover(pop[i],pop[i+1])

    print("child population genetypes after crossover",c)


    ##Mutation
    def mutation(p):
        for i in range(len(p)):
            r=np.random.randint(0,len(p[i]))
            #print(i,"genotype",r,"index inverted")
            p[i][r]=1-p[i][r]
        return p

    c=mutation(c)
    print("child population genetypes after mutation",c)


    '''finding child fitness
    fc,fitc=fitness(c)
    #print("child population phonotype",fc)
    print("child population fitness",fitc)'''


    ##finding probability of given phonotypes and sum
    def prob(arr,s):
        pb=np.empty((len(arr)), dtype='float') 
        for i in range(len(arr)):
            pb[i]=round(float(arr[i])/s,2)
        return pb


    ##Intermediate population
    intpop=np.concatenate([pop,c])
    print("Intermediate population genetypes",intpop)

    ipd,ipfit=fitness(intpop)
    #print("intermediate population Phonotypes",ipd)
    print("intermediate population fitness",ipfit)


    ipprob=prob(ipd,ipfit)
    wt=np.random.randint(0,100,(ipprob.shape))
    nipprob=wt*ipprob
    print("New intermediate population probability after weight calculation",nipprob)


    ##sorting population according to probabilities
    def sort(pop,prob):
        for i in range(len(prob)):
            for j in range(len(prob)):
                if(prob[i]<prob[j]):               
                    temp=prob[j]
                    prob[j]=prob[i]
                    prob[i]=temp

                    t=pop[j]+0
                    pop[j]=pop[i]
                    pop[i]=t
        newp=pop[4:]            
        return pop,prob,newp


    ##sorted new intermediate population
    sintpop,sipprob,pop=sort(intpop,nipprob)
    #print("sorted intermediate population genetypes",sintpop)
    #print("sorted intermediate population probability",sipprob)
    print("new",lp," population genetypes",pop)

    nftd,nft=fitness(pop)
    #print("new population fitness phonotypes",nftd)
    print("new",lp," population fitness",nft)
    print("\n\n")

Parent population [[0 1 1 0 0]
 [1 0 0 1 0]
 [0 1 0 1 1]
 [0 1 0 0 0]]
Parent population phonotypes [12 18 11  8]
Parent population fitness 49


TypeError: 'float' object cannot be interpreted as an integer

In [1]:
import numpy as np

In [352]:
pop=np.random.randint(0,2,(4,5))
print("Parent population ",pop)

('Parent population ', array([[0, 1, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 0, 0, 1, 1]]))


In [353]:
def bintodec(b):
    dec,p=0,0
    for i in range(len(b),0,-1): 
        dec+=b[i-1]*pow(2,p)
        p+=1
    return dec

In [354]:
def fitness(p):
    f=np.empty((len(p)), dtype='int')   
    for i in range(len(p)):
        f[i]=bintodec(p[i])
    return (f,sum(f))
    

f,fit=fitness(pop)
print("Parent population ",pop)
#print("Parent population decimal",f)
print("Parent population fitness",fit)

('Parent population ', array([[0, 1, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 0, 0, 1, 1]]))
('Parent population fitness', 65)


In [355]:
def crossover(p1,p2):
    d=np.random.randint(1,len(p1))
    print("parent ",p1,"parent ",p2,"divided at",d)
    c1=np.concatenate([p1[0:d],p2[d:]])
    c2=np.concatenate([p2[0:d],p1[d:]])
    return c1,c2

c=np.empty((pop.shape), dtype='int')
for i in range(0,(len(pop)/2)*2,2):
    c[i],c[i+1]=crossover(pop[i],pop[i+1])

print("child population after crossover",c)


('parent ', array([0, 1, 1, 0, 1]), 'parent ', array([0, 1, 0, 1, 0]), 'divided at', 2)
('parent ', array([1, 0, 1, 1, 1]), 'parent ', array([1, 0, 0, 1, 1]), 'divided at', 3)
('child population after crossover', array([[0, 1, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 0, 1, 1]]))


In [356]:

def mutation(p):
    for i in range(len(p)):
        r=np.random.randint(0,len(p[i]))
        #print(i,"genotype",r,"index inverted")
        p[i][r]=1-p[i][r]
    return p

c=mutation(c)
print("child population after mutation",c)

('child population after mutation', array([[0, 1, 1, 1, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 0, 0, 1, 0]]))


In [357]:
fc,fitc=fitness(c)
#print("child population decimal",fc)
print("child population fitness",fitc)

('child population fitness', 80)


In [358]:
def prob(arr,s):
    pb=np.empty((len(arr)), dtype='float') 
    for i in range(len(arr)):
        pb[i]=round(float(arr[i])/s,2)
    return pb

In [359]:
intpop=np.concatenate([pop,c])
print("intermediate population",intpop)

ipd,ipfit=fitness(intpop)
#print("intermediate population decimal",ipd)
print("intermediate population fitness",ipfit)

('intermediate population', array([[0, 1, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 0, 0, 1, 0]]))
('intermediate population fitness', 145)


In [360]:
ipprob=prob(ipd,ipfit)
wt=np.random.randint(0,100,(ipprob.shape))
nipprob=wt*ipprob
print("New intermediate population probability after weight calculation",nipprob)

('New intermediate population probability after weight calculation', array([ 0.27,  4.55,  7.04, 10.66,  0.5 , 16.  , 12.09, 11.64]))


In [361]:
def sort(pop,prob):
    for i in range(len(prob)):
        for j in range(len(prob)):
            if(prob[i]<prob[j]):               
                temp=prob[j]
                prob[j]=prob[i]
                prob[i]=temp
                
                t=pop[j]+0
                pop[j]=pop[i]
                pop[i]=t
    newp=pop[4:]            
    return pop,prob,newp
    
sintpop,sipprob,newp=sort(intpop,nipprob)
#print("sorted intermediate population genetypes",sintpop)
#print("sorted intermediate population probability",sipprob)
print("new population",newp)

nftd,nft=fitness(newp)
#print("new population fitness phonotypes",nftd)
print("new population fitness",nft)

('new population', array([[1, 0, 0, 1, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1]]))
('new population fitness', 85)


In [388]:
for i in range(5):
    for i in range(4):
        print("\\\ni is",i)


('\\\ni is', 0)
('\\\ni is', 1)
('\\\ni is', 2)
('\\\ni is', 3)
('\\\ni is', 0)
('\\\ni is', 1)
('\\\ni is', 2)
('\\\ni is', 3)
('\\\ni is', 0)
('\\\ni is', 1)
('\\\ni is', 2)
('\\\ni is', 3)
('\\\ni is', 0)
('\\\ni is', 1)
('\\\ni is', 2)
('\\\ni is', 3)
('\\\ni is', 0)
('\\\ni is', 1)
('\\\ni is', 2)
('\\\ni is', 3)


In [366]:
print("\nhi\nhow")


hi
how
