In [106]:
import numpy as np
import math

In [171]:
inp=np.array([1,2,2,1,1,2,3,2,1,2,2,3,2,2,2,1,2,3,2,2,1,3,2,1,1,2,3,1,2,3,1,2,1,2,2,2,1,1,3,2,2,1,2,2,1,1,2,3])
inp=inp.reshape(12,4)


array([], shape=(0, 4), dtype=int64)

In [50]:
oup=np.array([1,1,1,1,2,1,2,1,1,1,2,1])
oup=oup.reshape(12,1)
oup.shape

(12, 1)

In [120]:
t=np.where(oup==1)[0]
t

In [100]:

y=np.empty((len(s)), dtype='int')



In [103]:
z=np.empty((len(s)),dtype='int')
for i in range(len(s)):
    #print(i)
    print(np.where(oup==s[i])[0])
    #y[i]=z
    #y=np.concatenate([y,z])
    #y[i]=np.where(oup==s[i])[0]

print(z)
print(z.shape)

[ 0  1  2  3  5  7  8  9 11]
[ 4  6 10]
[             0 94677574805008]
(2,)


[9, 3]


In [180]:

def entropy(p):
    print(p)
    e=0
    s=sum(p)
    for i in range(len(p)):
        e+=-(round(float(p[i])/s*math.log(float(p[i])/s,2),3))
        print(e)
    return e



In [181]:
def func(op):
    print(op)
    s=np.unique(op)
    l=[]
    for i in range(len(s)):
        l.append(len(np.where(op==s[i])[0]))
    print(l)
    return entropy(l)

#np.unique(inp[0])



[1 1 1 2 2 1 1 2 1 1 2 1]
[8, 4]
[8, 4]
0.39
0.918


0.918

In [168]:
f=func(oup)
f

[1 2 2 1]
[2, 2]
1.0


1.0

In [176]:
inp[:,0]

array([1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1])

In [182]:
def fin(x,y):
    for i in range(len(x)):
        if x[i]=y[i]:
            
    

fin(inp[:,0],oup)

(array([1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1]), array([[1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [1]]))
